{
 "title": "SNMP",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": "label_values(ifHCInOctets,  job)"
   },
   { "name": "Filters" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "options": {
    "content": "<center>\n    <h1><strong>BRI</strong></h1>\n</center>\n"
   },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": {
    "content": "<center>\n    <h1><strong>Menara Brilian</strong></h1>\n</center>\n"
   },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "ping",
     "rawSql": "SELECT\r\n    SUM(CASE WHEN status = 0 THEN 1 ELSE 0 END) AS count_0,\r\n    COUNT(status) AS total\r\nFROM ping.bri_table;"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "ping",
     "rawSql": "SELECT\r\n    SUM(CASE WHEN status = 0 THEN 1 ELSE 0 END) AS count_0,\r\n    COUNT(status) AS total\r\nFROM ping.brilian_table;"
    }
   ]
  },
  {
   "title": "BRI",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "ping",
     "rawSql": "SELECT \r\n  description AS Deskripsi, \r\n  ip AS Alamat, \r\n  status AS Status \r\nFROM ping.bri_table"
    }
   ]
  },
  {
   "title": "Menara Brilian",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "ping",
     "rawSql": "SELECT \r\n  description AS Deskripsi, \r\n  ip AS Alamat, \r\n  status AS Status \r\nFROM ping.brilian_table"
    }
   ]
  },
  { "title": "SNMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} * 10",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$instance\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$instance\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$instance\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$instance\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{instance=\"$instance\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{instance=\"$instance\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{instance=\"$instance\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$instance\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{instance=\"$instance\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}